#!/usr/bin/env zsh

candidates=(Pavel Honza Petr Filip Adam Vašek Bob Ondra)
characters=(beavis.zen blowfish bong bud-frogs bunny cheese cower daemon default dragon dragon-and-cow elephant elephant-in-snake eyes flaming-sheep ghostbusters head-in hellokitty kiss kitty koala kosh luke-koala meow milk moofasa moose mutilated ren satanic sheep skeleton small sodomized stegosaurus stimpy supermilker surgery telebears three-eyes turkey turtle tux udder vader vader-koala www)
randCandidate=$[$RANDOM % ${#candidates[@]}+1]
randCharacter=$[$RANDOM % ${#characters[@]}+1]
cowsay -f ${characters[$randCharacter]} ${candidates[$randCandidate]}
